source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '13.0'

target 'GGFuncSliderViewController_Example' do
  pod 'GGFuncSliderViewController', :path => '../'

  pod 'MJRefresh'

  pod 'QMUIKit', '4.7.0'

  #pod 'QMUIKit/QMUIMainFrame'
 
  pod 'YYText'

  target 'GGFuncSliderViewController_Tests' do
    inherit! :search_paths

    
  end
end




post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end